### ISSUE TITLE
nullable does not get converted correctly

### ISSUE THREAD

**Issue by webmaster777** [instrumenta/openapi2jsonschema#24]
in a swagger 2.0 yaml file:
```yaml
# some property in a definition
      datumStart:
        type: string
        format: date
        example: '2019-01-13'
        nullable: true
```

when converted to schema:

## Actual output

```json
    "datumStart": {
      "nullable": true, 
      "type": "string", 
      "example": "2019-01-13", 
      "format": "date"
    }, 
```

## Expected output

```json
    "datumStart": {
      "type": ["string", "null"], 
      "example": "2019-01-13", 
      "format": "date"
    }, 
```
